name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies for all projects
      run: dotnet restore

    - name: Build all projects
      run: dotnet build --configuration Release --no-restore

    - name: List out directory contents
      run: |
          echo "Listing the contents of the GitHub workspace directory"
          ls ${{ github.workspace }}

          echo "Recursively listing all contents of the current directory"
          ls -R

    - name: Run unit tests
      run: dotnet test ${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal --configuration Release
   
    # Pack and publish logic package
    - name: Pack logic package
      run: dotnet pack ${{ github.workspace }}/AnimalAdoption.Common.Logic/AnimalAdoption.Common.Logic.csproj --no-build --configuration Release --output ./taa-common-logic/
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add GPR NuGet source
      run: nuget source add -Name "GitHub" -Source "https://nuget.pkg.github.com/jacobcheatley/index.json" -UserName jacobcheatley -Password ${{ secrets.GH_PACKAGES_PAT }}

    - name: Set NuGet API key
      run: nuget setApiKey ${{ secrets.GH_PACKAGES_PAT }} -Source "GitHub"

    - name: Push NuGet package
      run: nuget push *.nupkg -Source "GitHub" -SkipDuplicate
      working-directory: ./taa-common-logic/

    # Publish and build portal
    - name: Publish portal project in Release mode
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: drop
        path:  ${{ github.workspace }}/taa-portal/
        if-no-files-found: error
